#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage `basename $0` port <1-4>"
    exit 0
fi  


ADDR=$1
newAddr=$ADDR

if [ $ADDR -eq 1 ]; then
    newAddr=8
elif [ $ADDR -eq 2 ]; then
    newAddr=4
elif [ $ADDR -eq 3 ]; then
newAddr=2
elif [ $ADDR -eq 4 ]; then
    newAddr=1
else 
    echo "Usage `basename $0` port <1-4>"
    exit 0
fi


logic=`getConfigValue Hkd.config relaycontrol calpulserPortLSB`
port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`


echo $port $channel $ADDR $newAddr

RelayControlPSA -n 4 $port $channel $newAddr
