////////////////////////////////////////////////////////////////
// File - TURFIO_2_08DEC04.c
//
// To Test TURFIO boards--07DEC04 --To Be Checked
// linux/makefile_bk.TURF1
//
// Initial code was generated by DriverWizard v6.03 - http://www.jungo.com.
// The library accesses the hardware via WinDriver functions.
// 
////////////////////////////////////////////////////////////////

#include "testapp_lib.h"
#include "/root/WinDriver//samples/shared/pci_diag_lib.h"
#include <stdio.h>
#include "/root/WinDriver//include/status_strings.h"
#include <sys/timeb.h>
//#include "dalib.h"

#define VENDOR_ID 0x10b5
#define DEVICE_ID 0x9030
#define SCA_MAX 256
#define CHAN_MAX 8
#define EVT_MAX 100000
#define Avg_EVT_MAX 10
//#define EVT_MAX 100000
#define DALIDEBUG 0

// input command from user
static char line[256];
//Copied from lab_test9.c by JC-19OCT04
//static int ped[SCA_MAX][CHAN_MAX];

//int TESTAPP_BlockRead(TESTAPP_HANDLE hTESTAPP, TESTAPP_ADDR ad_sp, TESTAPP_MODE ad_mode, struct PCIData *D)
int TESTAPP_BlockRead(TESTAPP_HANDLE hTESTAPP, TESTAPP_ADDR ad_sp, TESTAPP_MODE ad_mode)
{
    int sca,chan,vizchan;
    UINT addr = 0;
    UINT start_err = 1;
    UINT stop_err = 1;
    UINT rawdata[SCA_MAX][CHAN_MAX];
    UINT data[SCA_MAX][CHAN_MAX];

    sca = 0;
    chan = 0;
    vizchan = 0;

    // garbage read -- needed to prime data readout from FIFO
    //
        rawdata[0][0] = TESTAPP_ReadWord(hTESTAPP, ad_sp, addr);
	//	data[sca][chan] = (rawdata[sca][chan])&0x0FFF;
	//	printf("Garbage data = %d \n\n",data[sca][chan]);

	for(sca=0;sca<SCA_MAX;sca++)
	  {
	    for(chan=0;chan<CHAN_MAX;chan++)
	      {
		rawdata[sca][chan] = TESTAPP_ReadWord(hTESTAPP, ad_sp, addr);
		//data[sca][chan] = (rawdata[sca][chan])&0x0FFF;
		data[sca][chan] = (rawdata[sca][chan])&0xFFFF;
		//	printf("Wilkinson data = %d \n\n",data[sca][chan]);
		if(chan == vizchan) {
	//	printf("Column, channel = %d, %d : %d \n",sca,chan,data[sca][chan]);	      
		}
//Copied from lab_test9.c
//		D->data[sca][chan] = (rawdata[sca][chan])&0x0FFF;
//		hitbus[sca][chan] = (rawdata[sca][chan])&0xF000;
//Copied from lab_test9.c
	      }
	  }

//Copied from lab_test9.c
	// implement comparison subtraction
/*
	for(sca=0;sca<SCA_MAX;sca++)
	  {
	    for(chan=1;chan<CHAN_MAX;chan++)
	      {
		//		printf("ped[sca][chan] = %d \n",ped[sca][chan]);
		D->data[sca][chan] = D->data[sca][chan] - D->data[sca][0] - ped[sca][chan];  // subtract 0 reference
		if((hitbus[sca][chan]) != 0) {
		  D->data[sca][chan] = 0; // assign to 0 for hitbus values
		}
		//		printf("sca = %d, chan = %d, D->data[sca][chan] = %d \n",sca,chan,D->data[sca][chan]);
		//		printf("pedestal %d subtracted D->data[sca][chan] = %d \n",ped[sca][chan],(D->data[sca][chan]-ped[sca][chan]));
	      }
	  }

	return 0;
//Copied from lab_test9.c
*/
	return data[sca][chan];
}


TESTAPP_HANDLE TESTAPP_LocateAndOpenBoard(DWORD dwVendorID, DWORD dwDeviceID)
{
    DWORD cards, my_card;
    TESTAPP_HANDLE hTESTAPP = NULL;

    if (dwVendorID==0)
    {
        printf ("Enter VendorID: ");
        fgets(line, sizeof(line), stdin);
        sscanf (line, "%x",&dwVendorID);
        if (dwVendorID==0) return NULL;

        printf ("Enter DeviceID: ");
        fgets(line, sizeof(line), stdin);
        sscanf (line, "%x",&dwDeviceID);
    }
    cards = TESTAPP_CountCards (dwVendorID, dwDeviceID);
    if (cards==0)
    {
        printf ("%s", TESTAPP_ErrorString);
        return NULL;
    }
    else if (cards==1)
        my_card = 1;
    else
    {
        UINT i;

if (DALIDEBUG)       printf ("Found %u matching PCI cards\n", (UINT)cards);
if (DALIDEBUG)        printf ("Select card (1-%u): ", (UINT)cards);
        i = 0;
        fgets(line, sizeof(line), stdin);
        sscanf (line, "%d",&i);
        if (i>=1 && i <=cards) my_card = i;
        else 
        {
            printf ("Choice is out of range\n");
            return NULL;
        }
    }
    if (!TESTAPP_Open (&hTESTAPP, dwVendorID, dwDeviceID, my_card - 1))
    {
        printf ("%s", TESTAPP_ErrorString);
        return NULL;
    }
if (DALIDEBUG)     printf ("TESTAPP PCI card found!\n");
    return hTESTAPP;
}

int main(int argc, char *argv[])
{
    FILE *LAB_avg;
    int cmd,evtnum,crud,stat,sdat[EVT_MAX];
    int Avg_evtnum, Avg_crud, Avg_stat, Avg_sdat[Avg_EVT_MAX];
    double Avg_avg, Avg_sum;
    DWORD write_surf, read_surf;
    int repeat0, repeat1, times, i_EOE;
    double avg,sum,dev,devsq,sumsq,stdev;
    DWORD dwOffset;
    DWORD dwVal;
    DWORD dwVal1, dwVal2, dwVal3, dwVal4, dwVal5;
    TESTAPP_HANDLE hTESTAPP = NULL;
    HANDLE hWD;
    struct timeb start_time;			//declaring start time
    struct timeb end_time;                      //declaring the end time  

    struct PCIData *D;

    ftime(&start_time);    			//getting start time of program
    
    printf ("\n TURFIO Rev. A diagnostic utility.\n");

    // Make sure WinDriver is loaded
    if (!PCI_Get_WD_handle(&hWD))
        return 0;
    WD_Close (hWD);

    hTESTAPP = TESTAPP_LocateAndOpenBoard(VENDOR_ID, DEVICE_ID);

if (hTESTAPP)
{
	dwOffset = 0x54;  // GPIOC address offset

//Force Trig_Clr(Clr_AllEvent) On
	dwVal = 0x192;  // force bit GPIO2=Clr_AllEvt On
	TESTAPP_WriteDword(hTESTAPP, 0, dwOffset, dwVal);
		dwVal = TESTAPP_ReadDword(hTESTAPP, 0, dwOffset);
		//printf("GPIOC Register set to: %x\n",dwVal);

//Force Trig_Clr(Clr_AllEvt) Off
	dwVal = 0x92;  // force bit GPIO2=Clr_AllEvt Off
	TESTAPP_WriteDword(hTESTAPP, 0, dwOffset, dwVal);
		dwVal = TESTAPP_ReadDword(hTESTAPP, 0, dwOffset);
		//printf("GPIOC Register set to: %x\n",dwVal);

	for (evtnum=0; evtnum<EVT_MAX; evtnum++)
	{

	    dwVal = 0x96; //Set GPIO0=Evt_Trig=1;
		TESTAPP_WriteDword(hTESTAPP, 0, dwOffset, dwVal);
		dwVal = TESTAPP_ReadDword(hTESTAPP, 0, dwOffset);
				//printf("GPIOC Register set to: %x\n",dwVal);


	    //if (hTESTAPP) crud = TESTAPP_BlockRead(hTESTAPP,2,TESTAPP_MODE_WORD);
	    if (hTESTAPP) crud = TESTAPP_ReadWord(hTESTAPP,2,0);
	      printf("    Event # = %d  ",evtnum);
	      printf("Crud data = %d \n",crud);

//Force Clr_Evt On
	dwVal=0xB2; // force bit GPIO1=Clr_Evt On
	TESTAPP_WriteDword(hTESTAPP, 0, dwOffset, dwVal);
		dwVal = TESTAPP_ReadDword(hTESTAPP, 0, dwOffset);
		//printf("GPIOC Register set to: %x\n",dwVal);

//Force Clr_Evt Off
	dwVal=0x92; // force bit GPIO1=Clr_Evt Off
	TESTAPP_WriteDword(hTESTAPP, 0, dwOffset, dwVal);
		dwVal = TESTAPP_ReadDword(hTESTAPP, 0, dwOffset);
		//printf("GPIOC Register set to: %x\n",dwVal);
	}

}
    
    if (hTESTAPP)
        TESTAPP_Close(hTESTAPP);

    return 0;
}
