/*! \file anitaCommand.h
  \brief Some command related thingummies
    
  Some simple definitions of the structures that we'll use to store 
  ANITA data. In here there will be the structures used for transient data,
  housekeeping stuff, GPS stuff and anything else that is going to be used
  by more than one of the processes. This will all change to use bit fields,
  at some point in the future. For now this is just a place holder we can
  test data flow with.

  August 2004  rjn@mps.ohio-state.edu
*/
#ifndef ANITA_COMMAND_H
#define ANITA_COMMAND_H

#define ACQD_ID_MASK 0x001
#define ARCHIVED_ID_MASK 0x002
#define CALIBD_ID_MASK 0x004
#define CMDD_ID_MASK 0x008
#define EVENTD_ID_MASK 0x010
#define GPSD_ID_MASK 0x020
#define HKD_ID_MASK 0x040
#define LOSD_ID_MASK 0x080
#define PRIORITIZERD_ID_MASK 0x100
#define SIPD_ID_MASK 0x200
#define MONITORD_ID_MASK 0x400
#define ALL_ID_MASK 0xfff

typedef enum {
    ID_FIRST =100,
    ID_ACQD = 100,
    ID_ARCHIVED,
    ID_CALIBD,
    ID_CMDD,
    ID_EVENTD,
    ID_GPSD,
    ID_HKD,
    ID_LOSD,
    ID_PRIORITIZERD,
    ID_SIPD,
    ID_MONITORD,
    ID_NOT_AN_ID
} ProgramId_t;

typedef enum {
    CMD_TAIL_VAR_LOG_MESSAGES = 1,
    CMD_TAIL_VAR_LOG_ANITA = 2,
    CMD_START_NEW_RUN = 3,
    CMD_MAKE_NEW_RUN_DIRS = 4,
    CMD_REALLY_KILL_PROGS = 127,
    CMD_SIPD_REBOOT = 128,
    CMD_SHUTDOWN_HALT = 129,
    CMD_REBOOT = 130,
    CMD_KILL_PROGS = 131,
    CMD_RESPAWN_PROGS =132,
    CMD_START_PROGS = 133,
    CMD_MOUNT = 134,
    CMD_WHITEHEAT= 135,
    CMD_MOUNT_NEXT_USB = 136,
    CMD_MOUNT_NEXT_BLADE = 137,
    CMD_EVENT_DISKTYPE = 138,
    CMD_HK_DISKTYPE = 139,
    ARCHIVE_STORAGE_TYPE = 140,
    ARCHIVE_PRI_DISK = 141,
    ARCHIVE_PRI_ENC_TYPE=142,
    ARCHIVE_ALTERNATE_USB = 143,
    ARCHIVE_DECIMATE_PRI = 144, 
    ARCHIVE_DEFAULT_FRAC = 145, //Not implemented
    TELEM_TYPE = 146,
    TELEM_PRI_ENC_TYPE = 147,
    ARCHIVE_PPS_PRIORITIES = 148,
    ARCHIVE_PPS_DECIMATE = 149,
    CMD_TURN_GPS_ON = 150,
    CMD_TURN_GPS_OFF = 151,
    CMD_TURN_RFCM_ON = 152,
    CMD_TURN_RFCM_OFF = 153,
    CMD_TURN_CALPULSER_ON = 154,
    CMD_TURN_CALPULSER_OFF = 155,
    CMD_TURN_VETO_ON = 156,
    CMD_TURN_VETO_OFF = 157,
    CMD_TURN_ALL_ON = 158,
    CMD_TURN_ALL_OFF = 159,
    SET_CALPULSER_SWITCH = 171,
    SET_CALPULSER_ATTEN = 172,
    SET_ATTEN_LOOP_PERIOD = 173,
    SET_SWITCH_LOOP_PERIOD = 174,
    SET_PULSER_OFF_PERIOD = 175,
    SET_CALIB_WRITE_PERIOD = 176,
    SET_ADU5_PAT_PERIOD = 180,
    SET_ADU5_SAT_PERIOD = 181,
    SET_G12_PPS_PERIOD = 182,
    SET_G12_PPS_OFFSET = 183,
    SET_ADU5_CALIBRATION_12 = 184,
    SET_ADU5_CALIBRATION_13 = 185,
    SET_ADU5_CALIBRATION_14 = 186,
    SET_ADU5_VTG_PERIOD = 187,
    SET_G12_POS_PERIOD = 188,
    SET_HK_PERIOD = 190,
    SET_HK_CAL_PERIOD = 191,
    SET_HK_TELEM_EVERY = 192,
    SIPD_SEND_WAVE = 195,
    SIPD_THROTTLE_RATE = 196,
    SIPD_PRIORITY_BANDWIDTH =197,
    LOSD_PRIORITY_BANDWIDTH =198,
    LOSD_SEND_DATA =199,
    CLEAN_DIRS = 200,
    CLEAR_RAMDISK = 201,
    SEND_CONFIG = 210,
    DEFAULT_CONFIG =211,
    SWITCH_CONFIG =212,
    LAST_CONFIG=213,
    SAVE_CONFIG=214,
    MONITORD_RAMDISK_KILL_ACQD = 220,
    MONITORD_RAMDISK_DUMP_DATA = 221,
    MONITORD_MAX_ACQD_WAIT = 222,
    MONITORD_PERIOD = 223,
    MONITORD_USB_THRESH = 224,
    MONITORD_BLADE_THRESH = 225,
    MONITORD_MAX_QUEUE = 226, 
    MONITORD_INODES_KILL_ACQD = 227, 
    MONITORD_INODES_DUMP_DATA = 228,          
    ACQD_ADU5_TRIG_FLAG = 230,
    ACQD_G12_TRIG_FLAG = 231,
    ACQD_SOFT_TRIG_FLAG = 232,
    ACQD_SOFT_TRIG_PERIOD = 233,
    ACQD_ENABLE_CHAN_SERVO = 234,
    ACQD_SET_PID_GOAL = 235,
    ACQD_PEDESTAL_RUN = 236,
    ACQD_THRESHOLD_SCAN =237,
    ACQD_SET_ANT_TRIG_MASK = 238,
    ACQD_SET_SURF_BAND_TRIG_MASK = 239,
    ACQD_SET_GLOBAL_THRESHOLD = 240,
    ACQD_REPROGRAM_TURF = 241,
    ACQD_SURFHK_PERIOD = 242,
    ACQD_SURFHK_TELEM_EVERY = 243,
    ACQD_TURFHK_TELEM_EVERY =244,
    ACQD_NUM_EVENTS_PEDESTAL = 245,
    ACQD_THRESH_SCAN_STEP_SIZE = 246,
    ACQD_THRESH_SCAN_POINTS_PER_STEP = 247,
    ACQD_CHAN_PID_GOAL_SCALE = 248,
    ACQD_SET_RATE_SERVO = 249,
    ACQD_SET_NICE_VALUE = 250,
    EVENTD_MATCH_GPS = 251,
    PRIORITIZERD_COMMAND =253    
} CommandCode_t;


typedef enum {
    PRI_HORN_THRESH=1,
    PRI_HORN_DESC_WIDTH=2,
    PRI_HORN_SECTOR_WIDTH=3,
    PRI_CONE_THRESH=4,
    PRI_CONE_DESC_WIDTH=5,
    PRI_HOLDOFF=6,
    PRI_DELAY=7,
    PRI_HORN_GUARD_OFFSET=8,
    PRI_HORN_GUARD_WIDTH=9,
    PRI_HORN_GUARD_THRESH=10,
    PRI_CONE_GUARD_OFFSET=11,
    PRI_CONE_GUARD_WIDTH=12,
    PRI_CONE_GUARD_THRESH=13,
    PRI_FFT_PEAK_MAX_A=14,
    PRI_FFT_PEAK_MAX_B=15,
    PRI_RMS_MAX=16,
    PRI_RMS_EVENTS=17,
    PRI_WINDOW_CUT=18,
    PRI_BEGIN_WINDOW=19,
    PRI_END_WINDOW=20,
    PRI_METHOD_MASK=21,
    PRI_FFT_MAX_CHANNELS=22,
    PRI_FFT_PEAK_WINDOW_L=23,
    PRI_FFT_PEAK_WINDOW_R=24
} PrioritizerdCommandCode_t;
    

#endif /* ANITA_COMMAND_H */
