#!/bin/bash
#
# SIPd        Starts SIPd
#
#
# description: SIPd is the program that talks to the SIP. It is 
#              quite important. 
### BEGIN INIT INFO
# Provides: $SIPd
### END INIT INFO

# Source function library.
. /etc/init.d/functions

[ -f /usr/bin/SIPd ] || exit 0


RETVAL=0

if [ -z "$SIPD_UMASK" ] ; then
      SIPD_UMASK=077;
fi
umask $SIPD_UMASK
SIPD_OPTIONS=-d

start() {
# 	echo -n $"Starting SIPd: "
	/usr/local/bin/daemon -u anita -r SIPd -n SIPd 
	RETVAL=$?
#	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/SIPd
	return $RETVAL
}	

stop() {
#	echo -n $"Shutting down SIPd: "
	/usr/local/bin/daemon --stop -n SIPd 
#	killproc SIPd
#	echo
	RETVAL=$?
#	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/SIPd
	return $RETVAL
}

rhstatus() {
	status SIPd
}

restart() {
	stop
	start
}	

case "$1" in
  start)
  	action $"Starting SIPd..." start
	;;
  stop)
  	action $"Stoping SIPd..." stop
	;;
  status)
  	rhstatus
	;;
  restart)
  	action $"Stoping SIPd..." stop
  	action $"Starting SIPd..." start
	;;
  condrestart)
  	[ -f /var/lock/subsys/SIPd ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac

exit $?

