#!/bin/sh -
#-----------------------------------------------------------------------------
#
#      File         :  sortOutSerials
#      Abstract     :  Makes some sensible symlinks based on FTDI serial number
#      Last Revision:  28-07-14
#-----------------------------------------------------------------------------


if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVP2XGY-if01-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVP2XGY-if01-port0` /dev/ttyADU5B
fi

if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVP2XGY-if02-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVP2XGY-if02-port0` /dev/ttyADU5A
fi


if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVP2XGY-if03-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVP2XGY-if03-port0` /dev/ttyMag
fi

if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if00-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if00-port0` /dev/ttyG12B
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if00-port0` /dev/gps1
fi


if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if01-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if01-port0` /dev/ttyG12A
fi


if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if02-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if02-port0` /dev/ttyHigh2
fi


if [ -L "/dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if03-port0" ]
then
    ln -sf `readlink -f /dev/serial/by-id/usb-FTDI_USB-COM232_Plus4_FTVQ0ZPH-if03-port0` /dev/ttyLow2
fi


### This is possibly the device used at Palestine; might change for Antarctica  -- CSD 
if [-L "/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0" ] 
then 
    ln -sf `readlink -f /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0` /dev/ttyTUFF 
fi 

ln -sf /dev/ttyS0 /dev/ttyLow1
ln -sf /dev/ttyS1 /dev/ttyHigh1
