#!/bin/bash
#
# SIPd        Starts SIPd
#
#
# chkconfig: 2345 12 88
# description: SIPd is the program that talks to the SIP. It is 
#              quite important. 
### BEGIN INIT INFO
# Provides: $SIPd
### END INIT INFO

# Source function library.
. /etc/init.d/functions

[ -f /usr/bin/SIPd ] || exit 0


RETVAL=0

if [ -z "$SIPD_UMASK" ] ; then
      SIPD_UMASK=077;
fi
umask $SIPD_UMASK
SIPD_OPTIONS=-d

start() {
 	echo -n $"Starting SIPd: "
	daemon --user=anita SIPd $SIPD_OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/SIPd
	return $RETVAL
}	

stop() {
	echo -n $"Shutting down SIPd: "
	killproc SIPd
	echo
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/SIPd
	return $RETVAL
}

rhstatus() {
	status SIPd
}

restart() {
	stop
	start
}	

reload()  {
    RETVAL=1
    SIPd=`cat /var/run/SIPd.pid 2>/dev/null`
    echo -n "Reloading SIPd..."
    if [ -n ${SIPd} ] && [ -e /proc/${SIPd} ]; then
	kill -HUP $SIPd;
	RETVAL=$?
    fi
    if [ $RETVAL -ne 0 ]; then
	fail
    else
	success
    fi
    echo
    return $RETVAL
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	rhstatus
	;;
  restart)
  	restart
	;;
  reload)
	reload
	;;
  condrestart)
  	[ -f /var/lock/subsys/SIPd ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac

exit $?

