#!/bin/bash

if [ -f /tmp/anita/pid/calibd.pid ]; then
    CmdTest 152
else
    logic=`getConfigValue Calibd.config relaycontrol turnBZAmpa1OnLogic`
    port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
    channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`
    
    RelayControlPSA $port $channel 0
    RelayControlPSA $port $channel 1
    RelayControlPSA $port $channel 0


    logic=`getConfigValue Calibd.config relaycontrol turnBZAmpa2OnLogic`
    port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
    channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`
    
    RelayControlPSA $port $channel 0
    RelayControlPSA $port $channel 1
    RelayControlPSA $port $channel 0
fi
