#!/bin/bash


if [ -f /tmp/anita/pid/calibd.pid ]; then
    CmdTest 159
else
    logic=`getConfigValue Calibd.config relaycontrol turnNtu5VLogic`
    port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
    channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`
    
    RelayControlPSA $port $channel 0
fi
