#!/bin/bash


if [ -f /tmp/anita/pid/calibd.pid ]; then
    CmdTest 156
else
    logic=`getConfigValue Hkd.config relaycontrol turnVetoOnLogic`
    port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
    channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`
    
    RelayControlPSA $port $channel 0
    RelayControlPSA $port $channel 1
    RelayControlPSA $port $channel 0
fi