#!/bin/bash

logic=`getConfigValue Hkd.config relaycontrol turnRFCM4OffLogic`
port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`

RelayControlPSA $port $channel 0
RelayControlPSA $port $channel 1
RelayControlPSA $port $channel 0
