#!/bin/bash

NTU_IP="[fe80::2e0:4bff:fe40:8074%p4p1]"

disabled=`getConfigValue anitaSoft.config global disableNtu`
if [ $disabled -eq 1 ] ; then
    echo "Ntu disk disabled"
    exit 0
fi


ntuName=`getConfigString anitaSoft.config global ntuName`
ntuCopyDir=`getConfigString anitaSoft.config global ntuCopyDir`

echo "ntuName: $ntuName"
echo "ntuCopyDir: $ntuCopyDir:"


while :
do
    rsync -av $NTU_IP:~/lastCopiedRun /tmp/lastCopiedRun

    #This first part just makes sure that any straggler files are copied correctly   
    LAST_RUN=`cat /mnt/data/numbers/lastRunNumber`
    START_RUN=`cat /tmp/lastCopiedRun`
    PENULTIMATE_RUN=`expr $LAST_RUN - 1`
    for run in `seq $START_RUN $PENULTIMATE_RUN`; do
	rsync -av ${ntuCopyDir}/run$run anita@${NTU_IP}:${ntuName}/  > /tmp/getRawData.log
	if  test `cat /tmp/getRawData.log  | wc -l` -gt 04 ; then
	    echo "Copied Run $run"
	    echo  $run > /tmp/lastCopiedRun
	    rsync -av /tmp/lastCopiedRun  $NTU_IP:~/lastCopiedRun
	fi
    done

    #Now try and copy only .gz files for current run
    rsync -av --exclude '*.dat' ${ntuCopyDir}/run${LAST_RUN} anita@${NTU_IP}:${ntuName}/  > /tmp/copyCurrentRun.log
    sleep 5
done
