#!/bin/bash

ADDR=$1

logic=`getConfigValue Hkd.config relaycontrol calpulserAddrLSB`
port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`

RelayControlPSA -n 4 $port $channel $ADDR
