#!/bin/bash

GAIN=$1

logic=`getConfigValue Hkd.config relaycontrol sunsensorGainLSB`
port=`echo $logic | awk '{printf("%d\n",$1/8);}'`
channel=`echo $logic | awk '{printf("%d\n",$1 % 8);}'`

RelayControlPSA -n 3 $port $channel $GAIN
